version: "3.3"

services:
  rna_db_server:
    container_name: dash_board_mysql
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: alpha_db
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3307:3306
